refactor: move Small test wip #153

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -31,97 +31,97 @@ env:
   flutter-channel: 'stable'
 
 jobs:
-  build:
-    name: 'Build on ${{ matrix.os }}'
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [ubuntu-latest, macos-latest, windows-latest]
-    runs-on: ${{ matrix.os }}
-    steps:
-      - uses: actions/checkout@v3
-      - name: 'Install Flutter'
-        uses: ./.github/actions/install-flutter
-        with:
-          version: ${{ env.flutter-version }}
-          channel: ${{ env.flutter-channel }}
-      - name: 'Install dependencies'
-        uses: ./.github/actions/install-dependencies
-      - name: 'Generate Localization code'
-        uses: ./.github/actions/generate-localization_code
-      - name: 'Build Mocks'
-        uses: ./.github/actions/build-mocks
-
-  analyze-production_code:
-    name: 'Analyze Production code'
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - name: 'Install Flutter'
-        uses: ./.github/actions/install-flutter
-        with:
-          version: ${{ env.flutter-version }}
-          channel: ${{ env.flutter-channel }}
-      - name: 'Install dependencies'
-        uses: ./.github/actions/install-dependencies
-      - name: 'Generate Localization code'
-        uses: ./.github/actions/generate-localization_code
-      - name: 'Flutter Doctor'
-        run: flutter doctor -v
-      - name: 'Analyze Production code'
-        run: flutter analyze lib
-
-  analyze-test_code:
-    name: 'Analyze Test code'
-    runs-on: ubuntu-latest
-    steps:
-      - name: 'Checkout code'
-        uses: actions/checkout@v3
-      - name: 'Install Flutter'
-        uses: ./.github/actions/install-flutter
-        with:
-          version: ${{ env.flutter-version }}
-          channel: ${{ env.flutter-channel }}
-      - name: 'Install dependencies'
-        uses: ./.github/actions/install-dependencies
-      - name: 'Build Mocks'
-        uses: ./.github/actions/build-mocks
-      - name: 'Flutter Doctor'
-        run: flutter doctor -v
-      - name: 'Analyze Test code'
-        run: flutter analyze test integration_test
-
-  small_test:
-    name: 'Small test'
-    runs-on: ubuntu-latest
-    steps:
-      - name: 'Checkout code'
-        uses: actions/checkout@v3
-      - name: 'Install Flutter'
-        uses: ./.github/actions/install-flutter
-        with:
-          version: ${{ env.flutter-version }}
-          channel: ${{ env.flutter-channel }}
-      - name: 'Install dependencies'
-        uses: ./.github/actions/install-dependencies
-      - name: 'Build Mocks'
-        uses: ./.github/actions/build-mocks
-      - name: 'Generate Localization code'
-        uses: ./.github/actions/generate-localization_code
-      - name: 'Flutter Doctor'
-        run: flutter doctor -v
-      - id: 'test_execution'
-        continue-on-error: true
-        run: flutter test --coverage
-      - name: 'Upload coverage'
-        uses: codecov/codecov-action@v3
-        with:
-          token: ${{ secrets.CODECOV_TOKEN }}
-          files: ./coverage/lcov.info
-          flags: small_test
-      - name: 'Error handling'
-        if: ${{ steps.test_execution.outcome == 'failure' }}
-        run: exit 1
+#  build:
+#    name: 'Build on ${{ matrix.os }}'
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        os: [ubuntu-latest, macos-latest, windows-latest]
+#    runs-on: ${{ matrix.os }}
+#    steps:
+#      - uses: actions/checkout@v3
+#      - name: 'Install Flutter'
+#        uses: ./.github/actions/install-flutter
+#        with:
+#          version: ${{ env.flutter-version }}
+#          channel: ${{ env.flutter-channel }}
+#      - name: 'Install dependencies'
+#        uses: ./.github/actions/install-dependencies
+#      - name: 'Generate Localization code'
+#        uses: ./.github/actions/generate-localization_code
+#      - name: 'Build Mocks'
+#        uses: ./.github/actions/build-mocks
+#
+#  analyze-production_code:
+#    name: 'Analyze Production code'
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v3
+#      - name: 'Install Flutter'
+#        uses: ./.github/actions/install-flutter
+#        with:
+#          version: ${{ env.flutter-version }}
+#          channel: ${{ env.flutter-channel }}
+#      - name: 'Install dependencies'
+#        uses: ./.github/actions/install-dependencies
+#      - name: 'Generate Localization code'
+#        uses: ./.github/actions/generate-localization_code
+#      - name: 'Flutter Doctor'
+#        run: flutter doctor -v
+#      - name: 'Analyze Production code'
+#        run: flutter analyze lib
+#
+#  analyze-test_code:
+#    name: 'Analyze Test code'
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: 'Checkout code'
+#        uses: actions/checkout@v3
+#      - name: 'Install Flutter'
+#        uses: ./.github/actions/install-flutter
+#        with:
+#          version: ${{ env.flutter-version }}
+#          channel: ${{ env.flutter-channel }}
+#      - name: 'Install dependencies'
+#        uses: ./.github/actions/install-dependencies
+#      - name: 'Build Mocks'
+#        uses: ./.github/actions/build-mocks
+#      - name: 'Flutter Doctor'
+#        run: flutter doctor -v
+#      - name: 'Analyze Test code'
+#        run: flutter analyze test integration_test
+#
+#  small_test:
+#    name: 'Small test'
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: 'Checkout code'
+#        uses: actions/checkout@v3
+#      - name: 'Install Flutter'
+#        uses: ./.github/actions/install-flutter
+#        with:
+#          version: ${{ env.flutter-version }}
+#          channel: ${{ env.flutter-channel }}
+#      - name: 'Install dependencies'
+#        uses: ./.github/actions/install-dependencies
+#      - name: 'Build Mocks'
+#        uses: ./.github/actions/build-mocks
+#      - name: 'Generate Localization code'
+#        uses: ./.github/actions/generate-localization_code
+#      - name: 'Flutter Doctor'
+#        run: flutter doctor -v
+#      - id: 'test_execution'
+#        continue-on-error: true
+#        run: flutter test --coverage
+#      - name: 'Upload coverage'
+#        uses: codecov/codecov-action@v3
+#        with:
+#          token: ${{ secrets.CODECOV_TOKEN }}
+#          files: ./coverage/lcov.info
+#          flags: small_test
+#      - name: 'Error handling'
+#        if: ${{ steps.test_execution.outcome == 'failure' }}
+#        run: exit 1
 
   medium_test:
     name: 'Medium test(${{ matrix.platform }})'
